# Generated by Django 3.0.3 on 2020-02-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('variety', models.CharField(choices=[('UN', 'Unseen'), ('P', 'Poop'), ('A', 'Advertisement'), ('E', 'Emergency')], max_length=2)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=60)),
                ('game_objects', models.ManyToManyField(to='debrand_game.GameObject')),
                ('next_levels', models.ManyToManyField(to='debrand_game.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=96)),
                ('score', models.IntegerField()),
                ('levels_played', models.ManyToManyField(related_name='player_of_this_level', to='debrand_game.Level')),
            ],
        ),
    ]
