# Generated by Django 3.0.3 on 2020-02-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debrand_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameobject',
            name='name',
            field=models.CharField(default='no', max_length=96),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='name',
            field=models.CharField(default='yes', max_length=96),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
