# Generated by Django 3.0.3 on 2020-02-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debrand_game', '0004_level_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='next_levels',
            field=models.ManyToManyField(blank=True, to='debrand_game.Level'),
        ),
    ]
