# Generated by Django 3.0.3 on 2020-02-17 17:23

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('debrand_game', '0005_auto_20200216_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='level',
            name='game_objects',
            field=models.ManyToManyField(blank=True, to='debrand_game.GameObject'),
        ),
    ]
