# Generated by Django 3.0.3 on 2020-02-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debrand_game', '0008_level_img_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameobject',
            name='variety',
            field=models.CharField(choices=[('UN', 'Unseen'), ('P', 'Poop'), ('A', 'Advertisement'), ('E', 'Emergency'), ('B', 'Branding')], max_length=2),
        ),
    ]
