# Generated by Django 3.0.3 on 2020-02-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debrand_game', '0009_auto_20200217_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameobject',
            name='variety',
            field=models.CharField(choices=[('UN', 'Unseen'), ('P', 'Poop'), ('A', 'Advertisement'), ('E', 'Emergency'), ('B', 'Branding'), ('L', 'Life')], max_length=2),
        ),
    ]
